### ISSUE TITLE
launch_benchmark.py : ImportError: No module named 'object_detection'

### ISSUE THREAD

**Issue by hubertdelassus** [IntelAI/models#29]
When running python launch_benchmark.py \
    --data-location /home/user/coco/output/ \
    --in-graph /home/user/ssd_resnet34_fp32_bs1_pretrained_model.pb \
    --model-source-dir /home/user/tensorflow/models \
    --model-name ssd-resnet34 \
    --framework tensorflow \
    --precision fp32 \
    --mode inference \
    --socket-id 0 \
    --batch-size=1 \
    --docker-image gcr.io/deeplearning-platform-release/tf-cpu.1-14 \
    --accuracy-only
I get an error:
load graph from: /in_graph/ssd_resnet34_fp32_bs1_pretrained_model.pb
Namespace(accuracy_only=True, batch_size=1, data_location='/dataset', input_graph='/in_graph/ssd_resnet34_fp32_bs1_pretrained_model.pb', num_inter_threads=1, num_intra_threads=8, results_file_path=None)
T
Traceback (most recent call last):
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 1072, in create_dataset
    import ssd_dataloader  # pylint: disable=g-import-not-at-top
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/ssd_dataloader.py", line 27, in <module>
    from object_detection.box_coders import faster_rcnn_box_coder
ImportError: No module named 'object_detection'

Note that this error occurs for FP32 and INT8 when using --accuracy-only.
When using --benchmark-only the scripts runs successfully.

It seems that PYTHONPATH is not properly transmitted to the docker environment.

**Comment by Leslie-Fang** [comment]
I can reproduce this issue:
_Traceback (most recent call last):
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/preprocessing.py", line 1072, in create_dataset
    import ssd_dataloader  # pylint: disable=g-import-not-at-top
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/ssd_dataloader.py", line 27, in <module>
    from object_detection.box_coders import faster_rcnn_box_coder
ImportError: No module named 'object_detection'_

**Comment by hubertdelassus** [comment]
I figured out that in step 1 of the instructions you git clone https://github.com/tensorflow/models.git
hence creating a directory "models". In step 6  you git clone https://github.com/IntelAI/models.git creating another "models" directory. These two directories should be renamed ~/tensorflowmodels and ~/IntelAImodels and kept independent of each other. This solution solves the "no module name object_detection for me."

Then further down the process, I eventually run in another error while loading the first image file from COCO dataset:
tensorflow.python.framework.errors_impl_InvalidArgumentError: StringToNumberOp could not correctly convert string: 00000379133.jpg [[{{node StringToNumber}}]] [[batch_processing/IteratorGetNext]]
The parser seems to not extract the integer from the file name..

**Comment by Leslie-Fang** [comment]
@hubertdelassus  Thanks, after taking your suggestion, it do solve the problem.
But why do you need to load the raw jpg images when running the inference?

**Comment by hubertdelassus** [comment]
Hi,
The instructions for accuracy measurements state to run:

python launch_benchmark.py
--data-location /home/user/coco/output/
--in-graph /home/user/ssd_resnet34_fp32_bs1_pretrained_model.pb
--model-source-dir /home/user/tensorflow/models
--model-name ssd-resnet34
--framework tensorflow
--precision fp32
--mode inference
--socket-id 0
--batch-size=1
--docker-image gcr.io/deeplearning-platform-release/tf-cpu.1-14
--accuracy-only

It differs from benchmark-only by adding reference to the COCO data set with –data-location.
What the docker script is really doing I did not reverse engineer.




The instructions state to run

**Comment by Leslie-Fang** [comment]
@hubertdelassus 
Find a solution to solve the problem, please refer to this issue: https://github.com/tensorflow/benchmarks/issues/408
and the pr request:
https://github.com/tensorflow/benchmarks/pull/409

**Comment by Leslie-Fang** [comment]
@hubertdelassus 
Find the root cause,
In the BKM, it suggest to use this commit id:7a9934df2afdf95be9405b4e9f1f2480d748dc40
of create_coco_tf_record.py to convert the data into tfrecord format.
However, in this commit-id, it use filename(*.jpg) as source-id.
```
157       'image/source_id': dataset_util.bytes_feature(
158           filename.encode('utf8')),
```
That's why our benchmark failed at StringToNumberOp .

The latest create_coco_tf_record.py  will use image_id as the source-id.
```
      'image/source_id':
          dataset_util.bytes_feature(str(image_id).encode('utf8')),
```
Using the  latest create_coco_tf_record.py  ,  it will fix your issue.

**Comment by Leslie-Fang** [comment]
> @hubertdelassus
> Find the root cause,
> In the BKM, it suggest to use this commit id:7a9934df2afdf95be9405b4e9f1f2480d748dc40
> of create_coco_tf_record.py to convert the data into tfrecord format.
> However, in this commit-id, it use filename(*.jpg) as source-id.
> 
> ```
> 157       'image/source_id': dataset_util.bytes_feature(
> 158           filename.encode('utf8')),
> ```
> 
> That's why our benchmark failed at StringToNumberOp .
> 
> The latest create_coco_tf_record.py will use image_id as the source-id.
> 
> ```
>       'image/source_id':
>           dataset_util.bytes_feature(str(image_id).encode('utf8')),
> ```
> 
> Using the latest create_coco_tf_record.py , it will fix your issue.

@hubertdelassus 
Hi, Have you tried this suggestion? Does it work?
I have made a update of the BKM in this PR: https://github.com/IntelAI/models/pull/33
Could you help to have a look?

**Comment by hubertdelassus** [comment]
Thanks Leslie for addressing this issue in a diligent manner. I tested the fix and the images are now read properly. However the resnet34-ssd benchmark script in accuracy-only still fails when starting inference. I opened another ticket for this separate issue.

**Comment by dmsuehir** [comment]
We recently released model workload containers for SSD-ResNet34 [FP32](https://software.intel.com/content/www/us/en/develop/articles/containers/ssd-resnet34-fp32-inference-tensorflow-container.html) and [Int8](https://software.intel.com/content/www/us/en/develop/articles/containers/ssd-resnet34-int8-inference-tensorflow-container.html) inference. These containers have all the code, dependency installs, and pretrained models needed to run the inference and accuracy scripts. All that you'll need to provide is the [preprocessed COCO dataset](https://github.com/IntelAI/models/tree/master/datasets/coco) and an output directory where log files will be written. The links above have instructions on how to run the containers for accuracy and inference. I ran these scripts for both FP32 and Int8 (both accuracy and inference scripts) to verify that they are working. The containers have "quick start scripts" (which are described in the docs), which make it easier to run common use cases. If you want to call the launch_benchmark.py script with your own args, you can still do that by giving the `python benchmarks/launch_benchmark.py ...` command instead of the quickstart script in the docker run command. For more information on how to do this, please see the [advanced container usages documentation](https://github.com/IntelAI/models/blob/master/quickstart/common/tensorflow/ModelPackagesAdvancedOptions.md#docker).

**Comment by dmsuehir** [comment]
Closing since it's been over 90 days with no activity
