### ISSUE TITLE
launch_benchmark.py:  ImportError: No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by hubertdelassus** [IntelAI/models#32]
When running python launch_benchmark.py
--data-location /home/user/coco/output/
--in-graph /home/user/ssd_resnet34_fp32_bs1_pretrained_model.pb
--model-source-dir /home/user/tensorflow/models
--model-name ssd-resnet34
--framework tensorflow
--precision fp32
--mode inference
--socket-id 0
--batch-size=1
--docker-image gcr.io/deeplearning-platform-release/tf-cpu.1-14
--accuracy-only
I get an error:

Inference for accuracy check.
Traceback (most recent call last):
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/models/ssd_model.py", line 507, in postprocess
    import coco_metric  # pylint: disable=g-import-not-at-top
  File "/tmp/benchmarks/scripts/tf_cnn_benchmarks/coco_metric.py", line 32, in <module>
    from pycocotools.coco import COCO
  File "/workspace/models/research/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/workspace/models/research/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: No module named 'pycocotools._mask'

The PYTHONPATH is :"/home/user/Tensorflowmodels/models/research:/home/user/Tensorflowmodels/models/research/slim"

/home/user/cocoapi/PythonAPI was compiled with python3.6 and pycocotools was copied to /home/user/Tensorflowmodels/models/research.

 The /home/user/IntelModelsAI/benchmarks/launch_benchmark.py is also run with python.6
I have spent some time debugging the issue without success.

**Comment by Leslie-Fang** [comment]
@hubertdelassus 
you need to install CPython firstly. then build the proto files.

**Comment by hubertdelassus** [comment]
The issue is that the benchmark script requires python2.7.
Python2.7 which will generate _mask.so when compiling cocoapi/PythonAPI, while python3.6 will generate _mask.python36m_x86_64.so which will not be recognised by the script.

To use Python2.7 on Centos7 you have to:
(1) Create a python2.7 virtual environment.
(2) Install Tensorflow from sources with python2.7 bindings (including bazel)
(3) Compile cocoapi/PythonAPI inside the virtual environment for python 2.7
(4) Execute all the BKM using the python 2.7 virtual environment.

**Comment by hubertdelassus** [comment]
After installing Tensorflow with python2.7 bindings and running benchmark with python2.7 I am able to read _mask.so. 
However I get another error immediately after reading the library:
File "/workspace/models/research/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /workspace/models/research/pycocotools/_mask.so: undefined symbol: _Py_ZeroStruct
The same instruction import pycocotools._mask as _mask executed outside of the benchmark script works:
(venv2.7) [user@aipg benchmarks]$ python
Python 2.7.10 (default, Aug  1 2019, 22:54:14) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycocotools._mask as _mask
>>>

The library _mask.so seems not compatible with what is downloaded by docker.

**Comment by hubertdelassus** [comment]
The BKM states that python 2.7 is the required python version. However, running the benchmark under python 2.7 with Tensorflow compiled with python 2.7 bindings, docker creates in ~/Tensorflowmodels/models/research/pycocotools a directory __pycache__  filled with python3.5 files:
coco.cpython-35.pyc  __init__.cpython-35.pyc  mask.cpython-35.pyc
The mismatching python versions generate:
ImportError: /workspace/models/research/pycocotools/_mask.so: undefined symbol: _Py_ZeroStruct

**Comment by dmsuehir** [comment]
We recently released a [model workload container for SSD-ResNet34 FP32 inference](https://software.intel.com/content/www/us/en/develop/articles/containers/ssd-resnet34-fp32-inference-tensorflow-container.html). This container has all the code, dependency code/installs, and pretrained models that are needed to run the model. All that you'll need to provide is the path to the [preprocessed COCO dataset](https://github.com/IntelAI/models/tree/master/datasets/coco) and an output directory where the log files will be written. The container also includes quick start scripts for common use cases. In your case, you can use the [`fp32_accuracy.sh`](https://github.com/IntelAI/models/blob/master/quickstart/object_detection/tensorflow/ssd-resnet34/inference/fp32/fp32_accuracy.sh) script, which is using the same parameters mentioned above (like batch size 1, socket 0, and accuracy only). 

Here's an example of how the container can be used to run the accuracy test for SSD-ResNet32:
```
DATASET_DIR=/home/user/coco/output
OUTPUT_DIR=/home/user/logs

docker run \
  --env DATASET_DIR=${DATASET_DIR} \
  --env OUTPUT_DIR=${OUTPUT_DIR} \
  --volume ${DATASET_DIR}:${DATASET_DIR} \
  --volume ${OUTPUT_DIR}:${OUTPUT_DIR} \
  --privileged --init -t \
  intel/object-detection:tf-2.3.0-imz-2.2.0-ssd-resnet34-fp32-inference \
  /bin/bash quickstart/fp32_accuracy.sh
```

If you prefer to not use the quickstart script or would like to call the launch_benchmark.py with different args, you can use the above command with `python benchmarks/launch_benchmark.py ...` instead of `/bin/bash quickstart/fp32_accuracy.sh`. For more information, please see the [model container advanced usages documentation here](https://github.com/IntelAI/models/blob/master/quickstart/common/tensorflow/ModelPackagesAdvancedOptions.md#docker).

**Comment by dmsuehir** [comment]
Closing since it's been over 90 days with no activity
